name: amber_test_app
secret_key_base: mV6kTmG3k1yVFh-fPYpugSn0wbZveDvrvfQuv88DPF8
port: (ENV["PORT"] ||= "3000").to_i
log: "::Logger.new(STDOUT)"
log_level: "::Logger::INFO"
color: true
port_reuse: true
process_count: (ENV[%(AMBER_PROCESS_COUNT)]? || 1).to_i
host: 0.0.0.0
ssl_key_file:
ssl_cert_file:
redis_url: "#{ENV[%(REDIS_URL)]? || %(redis://localhost:6379)}"
database_url: mysql://root@localhost:3306/amber_test_app_test
session:
  key: "amber.session"
  store: :signed_cookie
  expires: 0
secrets:
  description: Store your test secrets credentials and settings here.
