version: '2'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_app

  redis:
    image: redis
    command: redis-server
    ports:
      - 6379:6379

  spec:
    build: .
    command: bin/amber_spec
    environment:
      DATABASE_URL: 'postgres://postgres:password@postgres:5432/test_app'
      REDIS_URL: 'redis://redis:6379'
      AMBER_ENV: test
    depends_on:
      - redis
      - postgres
