on:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04

    container:
      image: crystallang/crystal

    steps:
      - name: Download source
        uses: actions/checkout@v3

      - name: Install shards
        run: shards install

      - name: Run tests
        run: bin/amber_spec