on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
      - name: Remove sqllite3 dev library
        run: sudo apt uninstall libsqlite3-dev
      - name: Download source
        uses: actions/checkout@v3

      - name: Install shards
        run: shards install

      - name: Run tests
        run: bin/amber_spec